// This file is automatically generated by AdonisJS.

import env from '#start/env'
import { defineConfig } from '@adonisjs/lucid'

const dbConfig = defineConfig({
  connection: 'postgres',
  connections: {
    postgres: {
      client: 'pg',
      connection: env.get('NODE_ENV') === 'production'
        ? {
            connectionString: env.get('DATABASE_PUBLIC_URL'),
            ssl: { rejectUnauthorized: false }
          }
        : {
            host: env.get('DB_HOST'),
            port: env.get('DB_PORT'),
            user: env.get('DB_USER'),
            password: env.get('DB_PASSWORD'),
            database: env.get('DB_DATABASE')
          }
    }
  }
})

export default dbConfig

//configuration for local database connection

// import env from '#start/env'
// import { defineConfig } from '@adonisjs/lucid'

// const dbConfig = defineConfig({
//   connection: env.get('DB_CONNECTION', 'postgres'),
//   connections: {
//     postgres: {
//       client: 'pg',
//       connection: {
//         host: env.get('DB_HOST', 'localhost'),
//         port: env.get('DB_PORT', 5432),
//         user: env.get('DB_USER', 'postgres'),
//         password: env.get('DB_PASSWORD', ''),
//         database: env.get('DB_DATABASE', 'your_local_db'),
//         ssl: env.get('NODE_ENV') === 'production' ?
//           { rejectUnauthorized: false } :
//           false
//       },
//       migrations: {
//         naturalSort: true,
//         paths: ['database/migrations']
//       },
//       debug: env.get('NODE_ENV') === 'development',
//     }
//   }
// })

// export default dbConfig
